config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users do
    get 'followsings' => 'relationships#follows'
    get 'followers' => 'relationships#followers'
  end
  get '/search', to: 'searchs#search'

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = BookComment.find(params[:id])
    @comment.destroy
    render :index
  end

    private
    def comment_params
      params.require(:book_comment).permit(:comment, :book_id, :user_id)
    end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<div class="new-comment">
  <%= form_with(model:[book, book_comment]) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/book_comments/_index.html.erb
<div class="comments">
   <% book.book_comments.each do |book_comment| %>
   <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30',format: 'no_image.jpg' %>
   <%= book_comment.comment %>
   <% if current_user.id == book_comment.user.id %>
   <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete , remote: true %>
   <% end %>
   <nav><%= book_comment.user.name %></nav>
   <% end %>
</div>

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { book: @book }) %>")
$("textarea").val('')