config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  resources :users do
    get 'followsings' => 'relationships#follows'
    get 'followers' => 'relationships#followers'
  end
  get '/search', to: 'searchs#search'

end

app/models/book.rb
class Book < ApplicationRecord
   belongs_to :user
   validates :title, presence: true
	 validates :body, presence: true,length: { maximum: 200}
	 has_many :favorites, dependent: :destroy
	 has_many :book_comments, dependent: :destroy
   def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
   end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@books = Book.all
    @book = Book.new
    @user = current_user
 
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end


  def show

    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
    redirect_to books_path
    end


  end

   def update
     @book = Book.find(params[:id])
     if @book.update(book_params)
       flash[:notice] = "You have creatad book successfully."
       redirect_to  book_path(@book.id)
     else
       @books = Book.all
       flash[:notice]= ' errors prohibited this obj from being saved:'
       render "edit"
     end
   end

   def destroy
     @book = Book.find(params[:id])
     @book.destroy
     redirect_to "/books"
   end

  private
    def book_params
    	params.permit(:title, :body)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody id="book">
    <% books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "show", book_path(book) %></td>
        <% if book.user == current_user %>
          <td><%= link_to "編集", edit_book_path(book) %></td>
          <td><%= link_to "削除", book_path(book), method: :delete, remote: true %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <div>
          <ul style="color: red">
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
            <% @book. errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
           <h4>Title</h4>
            <%= f.text_field :title %>
            <h4>Opinion</h4>
            <%= f.text_area :body %>
            <%= f.submit 'Update Book', class:"btn btn-success" %>
        <% end %>
           <%= link_to "Show", book_path(@book) %>
           <%= link_to "Back", books_path %>
      </div>
      </div>
   </div>
</main>


      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <div>
    <ul style="color: red">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
      <% @book. errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
      </ul>
  </div>
<% end %>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tboy>
            <tr></tr>
            <tr>
              <th>namae</th>
              <th><%= @user.name %></th>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tboy>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
           <div class="form-group">
             <%= f.label :Title %>
             <%= f.text_field :title %>
           </div>
           <div class="form-group">
             <%= f.label :Opinion %>
             <%= f.text_area :body%>
           </div>
           <div class="form-group">
             <%= f.submit "Create Book", class: "btn btn-success" %>
           </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
               <td>
                 <%= link_to user_path(book.user_id) do %>
                 <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, fallback: "no_image.jpg",size:'20x20',format: 'no_image.jpg' %>
               </td>
               <% end %>
               <td><%=link_to book.title, book_path(book.id)%></td>
               <td><%= book.body %></td>
               <td id="likes_buttons_<%= book.id %>">
                 <%= render partial: 'favorites/favorite-btn',locals: {book: book} %>
               </td>
               <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tboy>
            <tr></tr>
            <tr>
              <th>namae</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tboy>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user),class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @newbook, local:true do |f| %>
           <div class="form-group">
             <%= f.label :Title %>
             <%= f.text_field :title %>
           </div>
           <div class="form-group">
             <%= f.label :Opinion %>
             <%= f.text_area :body%>
           </div>
           <div class="form-group">
             <%= f.submit "Create Book", class: "btn btn-success" %>
           </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size:'50x50',format: 'no_image.jpg' %>
                   <nav>
                     <%= @book.user.name %>
                    </nav>
                   <% end %>


              <td><%= link_to @book.title %></td>
              <td><%= @book.body %></td>
              <td id="likes_buttons_<%= @book.id %>">
                 <%= render partial: 'favorites/favorite-btn',locals: {book: @book} %>
               </td>
              <td><%= link_to "#{@book.book_comments.count} コメント", book_path(@book.id) %></td>
              <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id),class:"btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id),class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "Are you sure？" %></td>
              <% end %>
            </tr>

          </tbody>

        </table>
        <li id="comments_area">
        <%= render partial: 'book_comments/index',locals: {book: @book } %>
      　</li>
        <%= render partial: 'book_comments/form',locals: {book: @book, book_comment: @book_comment} %>

      </div>
    </div>
  </div>
</main>